# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 */1 * * *'
  workflow_dispatch:
    inputs:
      cache:
        description: 'Cache'     
        required: false
        default: 'true'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache checked
      uses: actions/cache@v2
      if: ${{ github.event.inputs.cache == 'true' || github.event_name != 'push' }}
      with:
        path: ./checked.txt
        key: build-${{ github.run_id }}
        restore-keys: |
          build-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        qfrom: ${{ secrets.mail_account }}
        qpass: ${{ secrets.mail_password }}
        token: ${{ secrets.token }}
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: |
          python -u biliSteam.py
