# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache checked
      uses: actions/cache@v2
      with:
        path: ~/checked.txt
        key: build-${{ github.run_id }}
        restore-keys: |
          build-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout pytools
      uses: actions/checkout@v2
      with:
        repository: 'w311ang/pytools'
        path: './pytools'
    - name: Setup pytools
      run: |
        cp ./pytools/pytools.py .
    - name: Run
      env:
        qfrom: ${{ secrets.qfrom }}
        qpass: ${{ secrets.qpass }}
      run: |
        ls
        python biliSteam.py
